#ifndef RESOUCELIBRARYPLUGIN_GLOBAL_H
#define RESOUCELIBRARYPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESOUCELIBRARYPLUGIN_EXPORT
# define RESOUCELIBRARYPLUGIN_API Q_DECL_EXPORT
#else
# define RESOUCELIBRARYPLUGIN_API Q_DECL_IMPORT
#endif

#endif // RESOUCELIBRARYPLUGIN_GLOBAL_H
