#ifndef MATERIALMANAGERPLUGIN_GLOBAL_H
#define MATERIALMANAGERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MATERIALMANAGERPLUGIN_EXPORT
# define MATERIALMANAGERPLUGIN_API Q_DECL_EXPORT
#else
# define MATERIALMANAGERPLUGIN_API Q_DECL_IMPORT
#endif

#endif // MATERIALMANAGERPLUGIN_GLOBAL_H
