#ifndef CORE_COREPLUGINGLOBAL_H
#define CORE_COREPLUGINGLOBAL_H

#include <QtCore/qglobal.h>

#ifdef COREPLUGIN_EXPORT
# define COREPLUGIN_API Q_DECL_EXPORT
#else
# define COREPLUGIN_API Q_DECL_IMPORT
#endif

#endif // CORE_COREPLUGINGLOBAL_H
