#ifndef RESOURCELIBRARY_RESOUCELIBRARYPLUGIN_GLOBAL_H
#define RESOURCELIBRARY_RESOUCELIBRARYPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RESOUCELIBRARYPLUGIN_EXPORT
# define RESOUCELIBRARYPLUGIN_API Q_DECL_EXPORT
#else
# define RESOUCELIBRARYPLUGIN_API Q_DECL_IMPORT
#endif

#endif // RESOURCELIBRARY_RESOUCELIBRARYPLUGIN_GLOBAL_H
