#ifndef JUICEJUMPERSPROJECTPLUGIN_GLOBAL_H
#define JUICEJUMPERSPROJECTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef JUICEJUMPERSPROJECTPLUGIN_EXPORT
# define JUICEJUMPERSPROJECTPLUGIN_API Q_DECL_EXPORT
#else
# define JUICEJUMPERSPROJECTPLUGIN_API Q_DECL_IMPORT
#endif

#endif // JUICEJUMPERSPROJECTPLUGIN_GLOBAL_H
