#ifndef PLUGIN_JUICEJUMPERSPROJECTPLUGINGLOBAL_H
#define PLUGIN_JUICEJUMPERSPROJECTPLUGINGLOBAL_H

#include <QtCore/qglobal.h>

#ifdef JUICEJUMPERSPROJECTPLUGIN_EXPORT
# define JUICEJUMPERSPROJECTPLUGIN_API Q_DECL_EXPORT
#else
# define JUICEJUMPERSPROJECTPLUGIN_API Q_DECL_IMPORT
#endif

#endif // PLUGIN_JUICEJUMPERSPROJECTPLUGINGLOBAL_H
