#ifndef WORKSPACE_WORKSPACEPLUGINGLOBAL_H
#define WORKSPACE_WORKSPACEPLUGINGLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WORKSPACEPLUGIN_EXPORT
# define WORKSPACEPLUGIN_API Q_DECL_EXPORT
#else
# define WORKSPACEPLUGIN_API Q_DECL_IMPORT
#endif

#endif // WORKSPACE_WORKSPACEPLUGINGLOBAL_H
