#ifndef FONTMANAGERPLUGIN_GLOBAL_H
#define FONTMANAGERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FONTMANAGERPLUGIN_EXPORT
# define FONTMANAGERPLUGIN_API Q_DECL_EXPORT
#else
# define FONTMANAGERPLUGIN_API Q_DECL_IMPORT
#endif

#endif // FONTMANAGERPLUGIN_GLOBAL_H
