#ifndef IMAGEDANIMATIONPLUGIN_GLOBAL_H
#define IMAGEDANIMATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMAGEDANIMATIONPLUGIN_EXPORT
# define IMAGEDANIMATIONPLUGIN_API Q_DECL_EXPORT
#else
# define IMAGEDANIMATIONPLUGIN_API Q_DECL_IMPORT
#endif

#endif // IMAGEDANIMATIONPLUGIN_GLOBAL_H
